import type { Metadata } from "next";

import Sidebar from "@/components/Sidebar";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

            <body>
                <div className='flex container mx-auto'>
                    <div className="w-1/4">
                    <Sidebar />
                    </div>
                    <div className="w-full">{children}</div>
                </div>
            </body>
        </html>
    );
}
