import type { Metadata } from "next";

import Sidebar from "@/components/Sidebar";
import DashboardNavbar from "@/components/DashboardNav";


export const metadata: Metadata = {
    title: "Landing Page design",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

            <body>
                <DashboardNavbar />
                <div className='flex'>
                    <div className="w-1/3">
                        <Sidebar />
                    </div>
                    <div className="w-full bg-muted">{children}</div>
                </div>
            </body>
        </html>
    );
}
